import { Geist, Geist_Mono } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <header className="header">
          {/* 이미지와 문구를 누르면 홈으로 이동 */}
          <Link href="/" className="logo">
            <Image
              src="/images/workout-logo.svg"
              alt=""
              width={44}
              height={44}
              className="logo-image"
            />

            <span>운동의 시작을, 더쉽게</span>
          </Link>

          <nav>
            <Link href="/">운동 찾기</Link>
            <Link href="/login">로그인</Link>
            <Link href="/signup">회원 가입</Link>
          </nav>
        </header>

        <main className="container">{children}</main>
      </body>
    </html>
  );
}
