import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <header className="header">
          <Link href={"/"} className="logo">운동의 시작을, 더쉽게</Link>
          <nav>
            <Link href={"/"}>운동 찾기</Link>
            <Link href={"/login"}>로그인</Link>
            <Link href={"/signup"}>회원 가입</Link>  
          </nav>
        </header>

        <main className="container">{ children }</main>  

      </body>
    </html>
  );
}
